#!/usr/bin/env python3

import os
import json
import locale
import sys
import reports
import emails

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"car": "",
    "sales_quantity": 0}
  annual_sales = {}
  most_popular_year = {"year": 0,
    "sales": 0
  }

  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    if item["total_sales"] > max_sales["sales_quantity"]:
      max_sales["sales_quantity"] = item["total_sales"]
      max_sales["car"] = item["car"]["car_model"]

    # TODO: also handle most popular car_year
    if item["car"]["car_year"] in annual_sales:
      annual_sales[item["car"]["car_year"]] = annual_sales[item["car"]["car_year"]] + item["total_sales"]
    else:
      annual_sales[item["car"]["car_year"]] = item["total_sales"]

  for year, sales in annual_sales.items():
    if sales > most_popular_year["sales"]:
      most_popular_year["year"] = year
      most_popular_year["sales"] = sales

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
      max_sales["car"], max_sales["sales_quantity"]),
    "The most popular year was {} with {} sales.".format(
      most_popular_year["year"], most_popular_year["sales"])
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report
  table = cars_dict_to_table(data)
  reports.generate("/tmp/cars.pdf","Sales summary for last month", "<br/>".join(str(element) for element in summary), table)
  # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  recipient = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = "The same summary from the PDF, but using \n between lines"
  message = emails.generate(sender, recipient, subject, body, "/tmp/cars.pdf")
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)